const HTTP_OK_STATUS = 200;
const HTTP_OK_POSTED = 201;
const HTTP_OK_DELETED = 204;
const HTTP_FAIL = 400;
const HTTP_FAIL_NOTAUTH = 401;
const HTTP_OK_FAIL = 404;

module.exports = {
  HTTP_OK_STATUS, HTTP_OK_POSTED, HTTP_OK_DELETED, HTTP_OK_FAIL, HTTP_FAIL, HTTP_FAIL_NOTAUTH };